name: build-linux
on: push
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev git -y
      - uses: dtolnay/rust-toolchain@nightly
      - uses: extractions/setup-just@v1
      - name: Build
        run: cargo build --release
      - name: Dist
        run: just dist_dir
      - uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: dist/
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Build
        run: cargo build --release
      - name: Dist
        run: just dist_dir
      - uses: actions/upload-artifact@v3
        with:
          name: MacOS
          path: dist/
# TODO: build-windows
